// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hamehnvxbhngxkbekrls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhbWVobnZ4YmhuZ3hrYmVrcmxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTI5MjUsImV4cCI6MjA3MTQyODkyNX0.TN7ZHO0LwVfrZ7JQMou5kQ0LBrwUNmUBdJZIlpUkLx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});